server:
  port: 8082
  servlet:
    context-path: /userservice

cors-origin: "http://localhost:63342"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MicroOpsHub
    username: microops
    password: MicroOps#123
  jpa:
    hibernate:
      ddl-auto: update  # auto-creates tables from entities
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
